import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "../components/header";
import isp from "../ASSETS/isorrowproductions.jpg"
import heart from "../ASSETS/HEART ICON.png"
import Image from "next/image";
import Link from "next/link";
export default function Home() {
    interface influencerData {
        amount:string,
        name:string,
        occupation:string,
        src:string,
        href:string
    }

    function parseCard ({amount,name,occupation,src,href}:influencerData) {

        return (
            <div id="item1" className="carousel-item w-full min-h-[400px] justify-center flex flex-col mb-4 ">
                <div className={"w-[150px] h-[90px] mb-4 border-accent border-2 rounded-lg bg-neutral m-auto"}>

                    <Image src={heart.src} alt={"hear"} width={32} height={32} className={"m-auto mt-4"}/>
                    <p className={"text-accent text-center text-3xl font-light"}>{amount}</p>

                </div>
                <Image width={240} height={200} src={src} className="w-full h-[200px] m-auto object-none mask mask-circle"/>
                <div>
                    <p className={"text-primary text-center text-3xl "}>{name}</p>
                    <div className="divider w-[50%] m-auto heart"></div>
                    <p className={"text-primary text-center"}>{occupation}</p>
                </div>
                <Link href={href} className={"m-auto"}><button className={"w-[122px] h-[42px] text-accent rounded-3xl mt-4 text-lg  m-auto bg-neutral border-accent border-2"}>Gratitud</button></Link>
            </div>
        )
    }
    return (
        <div data-theme={"mytheme"} className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={""}>
                <Header url={"/"}/>
                <div className={"lg:w-[1300px] flex lg:flex-row flex-col relative top-[128px] m-auto "}>
                    <div className={"flex flex-col lg:w-[900px] w-[650px] mr-64 mt-24"}>
                        <h1 className={"text-primary text-5xl lg:ml-24 font-bold "}>Recibe y gestiona el cariño de tus seguidores para seguir creando y contribuyendo al mundo</h1>
                        <p className={"text-primary text-2xl lg:ml-24 font-mono "}>"La gratitud es uno de los sentimientos mas poderosos que puedes experimentar, y compartirlo es un privilegio
                             que llenal el alma de alegria en quien lo da y en quien lo recibe" </p>

                    </div>
                    <div className={"divider lg:hidden mt-12"}/>
                    <div className={"w-[400px] m-auto lg:mt-0 mt-12 bg-accent bg-opacity-10 border-2 p-8 min-h-[600px] flex flex-col justify-center rounded-xl border-accent"}>
                        <div className={""}>
                            <div className="carousel w-full m-auto ">
                                {parseCard({amount:"719k", name:"ISorrowProductions",occupation:"Professional Goblin", src:isp.src, href:"/"})}
                                <div id="item2" className="carousel-item w-full">
                                    <img src="https://placeimg.com/800/200/arch" className="w-full"/>
                                </div>
                                <div id="item3" className="carousel-item w-full">
                                    <img src="https://placeimg.com/800/200/arch" className="w-full"/>
                                </div>
                                <div id="item4" className="carousel-item w-full">
                                    <img src="https://placeimg.com/800/200/arch" className="w-full"/>
                                </div>
                            </div>
                            <div className="flex justify-center w-full py-2 gap-2">
                                <a href="#item1" className="btn btn-xs">1</a>
                                <a href="#item2" className="btn btn-xs">2</a>
                                <a href="#item3" className="btn btn-xs">3</a>
                                <a href="#item4" className="btn btn-xs">4</a>
                            </div>
                        </div>

                    </div>
                </div>
            </main>
            <div className={"fixed w-[100vw] top-0 z-[-1] h-[100vh] bg-neutral left-0"}/>

        </div>
    )
}
