import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "../components/header";
import isp from "../ASSETS/isorrowproductions.jpg"
import heart from "../ASSETS/HEART ICON.png"
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import axios from "axios";
import {userApiForm} from "../types/userdata";
import {response} from "../types/api";
import {json} from "stream/consumers";

export default function Home() {
    interface influencerData {
        amount:string,
        name:string,
        occupation:string,
        src:string,
        href:string
    }
    async function submitForm(e:any) {
        e.preventDefault()
        const userData:userApiForm = {
            username:e.target.nombre.value,
            password:e.target.contrasena.value,
            creatorLink:e.target.link.value,
            email:e.target.email.value
        }
        let error="Unknown error has occurred"
        await axios({url:"/api/users/profile",method:"POST",data:userData}).then(
                function(e){
                    const {data,status}:response = e.data
                switch(status){
                    case "passed":
                        localStorage.setItem("userdata",JSON.stringify({username:userData.username,password:userData.password}))
                        error=""
                        break
                    case "rejected":
                        error = data
                        break
                }
        }).finally(function SetError(){
            useError(error)
        })

    }
    const form = [<div className={`z-[5] slidein relative`}>
        <p className={"text-2xl h-[32px] text-primary text-left m-auto"}>Que link deseas?</p>
        <div className={"w-[620px]  bg-base-200 p-4 border-2 rounded-2xl pl-2 border-accent bg-opacity-50 shadow-xl flex justify-start"}>
            <p className={"text-xl font-mont border-primary h-[32px] text-primary text-left"}>www.gratitud.com/</p>
            <input name={"link"} className={"text-xl font-mont border-primary relative top-[-2px] ml-1 w-[100%] outline-0 relative bg-opacity-0 bg-primary text-primary text-left"} placeholder={"tu url aca"}/>
        </div>
    </div>,
        <div className={`z-[10] slidein  mt-12 relative`}>
            <p className={"text-2xl text-primary text-left m-auto"}>Que nombre deseas?</p>
            <div className={"w-[620px] bg-base-200 border-2 p-4 border-accent rounded-2xl bg-opacity-50 shadow-xl flex justify-start"}>
                <input name={"nombre"} className={"text-xl relative top-[-2px] w-[100%] ml-1 outline-0 relative bg-opacity-0 bg-primary text-primary text-left"} placeholder={"tu nombre aca"}/>
            </div>
        </div>,
        <div className={`z-[10] slidein  mt-12 relative`}>
            <p className={"text-2xl h-[32px] text-primary text-left m-auto"}>Que contraseña deseas?</p>
            <div className={"w-[620px] border-2 p-4 border-accent rounded-2xl bg-base-200 bg-opacity-50 shadow-xl flex justify-start"}>
                <input name={"contrasena"} className={"text-xl font-mont border-primary relative top-[-2px] w-[100%] ml-e outline-0 relative bg-opacity-0 bg-primary text-primary text-left"} placeholder={"tu contraseña aca"}/>
            </div>
        </div>,
        <div className={`z-[10] slidein  mt-12 relative`}>
            <p className={"text-2xl h-[32px] text-primary text-left m-auto"}>Que email deseas?</p>
            <div className={"w-[620px] border-2 p-4 border-accent rounded-2xl bg-base-200 bg-opacity-50 shadow-xl flex justify-start"}>
                <input name={"email"} className={"text-xl font-mont border-primary relative top-[-2px] w-[100%] ml-e outline-0 relative bg-opacity-0 bg-primary text-primary text-left"} placeholder={"tu email aca"}/>
            </div>
        </div>,
    ]
    const [level,useLevel] = useState(1), [error,useError] = useState("");

    return (
        <div data-theme={"mytheme"} className={""}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={"m-auto bg-neutral"}>
                <Header url={"/signup"}/>
                <div className={"flex m-auto top-[94px] relative flex-col justify-center text-center"}>
                    <div className={"text-3xl h-[32px] text-primary text-center inline-flex m-auto  mt-24"}>Crea una cuenta con tu <p className={"text-3xl font-bold underline ml-1 mr-1"}> URL </p> personalizado <p className={"text-3xl font-bold underline ml-1 align-text-top"}>gratis</p></div>
                    <div className={"m-auto mt-12 w-[620px] relative"}>
                        <form onSubmit={submitForm}>

                        <p className={"text-2xl h-[32px] text-accent underline text-center m-auto"}>{error}</p>

                        {
                            form.splice(0,level)
                        }
                        {form.length>0 ?
                            <button type={"button"} onClick={function SetLevel(){
                                useLevel(level+1)
                            }} className={`mt-12 m-auto hardbtn transition-all p-2 rounded-3xl pl-4 pr-4`}>Siguiente</button>
                            :
                            <button type={"submit"} className={`mt-12 m-auto hardbtn p-2 rounded-3xl pl-4 pr-4`}>Crear cuenta</button>
                        }
                        </form>



                    </div>
                </div>
            </main>
            <div className={"fixed w-[100vw] top-0 z-[-1] h-[100%] bg-neutral left-0"}/>

        </div>
    )
}
